sudo: false
language: c
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_wait 30 stack install idris
- mkdir -p ~/bin
- export PATH=$HOME/bin:$PATH
install:
- cd $TRAVIS_BUILD_DIR/haskell; stack setup
- curl https://raw.githubusercontent.com/tototoshi/sbt-install/master/sbt-install > ~/bin/sbt-install && chmod 0755 ~/bin/sbt-install
- sbt-install 0.13.9
script:
- cd $TRAVIS_BUILD_DIR/haskell; stack --no-terminal test --no-haddock-deps
- cd $TRAVIS_BUILD_DIR/idris; make test
- cd $TRAVIS_BUILD_DIR/scala; sbt test

